sudo: required
services:
    - docker

before_install:
    - docker build -t sankethiyer/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true  sankethiyer/react-test npm test

after_success:
    - docker build -t sankethiyer/multi-client ./client
    - docker build -t sankethiyer/multi-nginx ./nginx
    - docker build -t sankethiyer/multi-server ./server
    - docker build -t sankethiyer/multi-worker ./worker
    # login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #push to docker hub
    - docker push sankethiyer/multi-client
    - docker push sankethiyer/multi-nginx
    - docker push sankethiyer/multi-server
    - docker push sankethiyer/multi-worker
